name: IVS Inspector Prerequisites
on:
  push:
    branches:
      - "main"
      - "release/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Set NPM package-lock false
        run: npm config set package-lock false
      - name: Build Project
        run: yarn build
      - name: Deploy Project
        run: echo "Deploying ..."
